### ISSUE TITLE
slate-react updateSelection causing scrollable modal to toggle scroll position between two places on every key press.

### ISSUE THREAD

**Issue by mattmazzola** [ianstormtaylor/slate#1551]
#### Do you want to request a *feature* or report a *bug*?
**Bug**

#### What's the current behavior?
The slate editor is inside a modal and every time I press a key it toggles between scrolling to the top of modal and scrolling to make selection centered. You can see in the video/gif below.

I start typing `tttttt` inside a slate editor and you can see the modal scroll position jump up and down for each key making the UI unusable.  

![image](https://user-images.githubusercontent.com/2856501/35247104-fab3ff04-ff7d-11e7-9987-5672df7ee4ef.png)

http://recordit.co/wv0eUzT9lE

I tried debugging the scroll even in chrome and it seems to becoming from the `updateSelection` method inside `slate-react` `content.js` whenever the component updates.

Example: https://github.com/ianstormtaylor/slate/blob/df5b4a5d6146034187b446a7cca4ce512f5477e4/packages/slate-react/src/components/content.js#L313

Which then calls this:

```
  if (isWindow) {
    window.scrollTo(x, y)
  } else {
    scroller.scrollTop = y
    scroller.scrollLeft = x
  }
```

https://github.com/ianstormtaylor/slate/blob/df5b4a5d6146034187b446a7cca4ce512f5477e4/packages/slate-react/src/utils/scroll-to-selection.js#L168

OS: Windows 10 (Version 10.0.16299 Build 16299)
Browser: Chrome 63.0.3239.132 (Official Build) (64-bit)
Slate: 0.31.3
Slate-React: 0.10.17

#### What's the expected behavior?
It should not keep scrolling to different places.  

I think somehow it's computing the (x,y) then scrolling so that one the next key press there is new relative (x,y) because it moved, then it jumps back and repeats the cycle. perhaps the x/y are calculated incorrectly in a certain scenario.

I noticed if I'm already scrolled all the way to the top of the modal or all the way to the bottom of the modal the issue does not occur. The bug only occurs when I'm initially scrolled in the middle of a modal.

**Comment by zGrav** [comment]
Could we get a jsfiddle of this @mattmazzola ?

Thanks!

**Comment by ch1ll0ut1** [comment]
I just encountered a similar problem about weird up scrolling.

When executing a addMark or a wrapInline for a selection at the lower end of the editor. And the editor having several pages of browser height. It will scroll up.
The Change is triggered when the Selection is already blurred (and the error happens with and without restoring the selection)

**Comment by zGrav** [comment]
@ch1ll0ut1 is there an issue for this? Could be a good one to open as well 👍

**Comment by mattmazzola** [comment]
Yea, I will work to create a fiddle, but might take me a bit since this one requires a bit more setup.  I'll also try to debug more in that scroll function to see which values are changing.

I was hoping maybe someone else was familiar with it and could explain work around just by seeing it.

**Comment by mattmazzola** [comment]
Ok, I was able to reproduce in isolation:
Example:
http://slatejs-scroll-bug-01.surge.sh/

Steps to reproduce:
1. Open the modal
2. Scroll down about half way in the modal then start typing in one of the inputs
(Notice the jumping of scroll bar)

Video: http://recordit.co/43pCjIuAjk

Note: When entering text the very top or very bottom editor the issue does not occur. Only when in the middle.
Also, I tried the same thing in Edge browser and the issue does not seem to occur.  Perhaps there is some browser differences in the computation of bounding boxes, offsets, etc used inside slates scrollToSelection method linked in OP.

For some strange reason I wasn't able to get it working within a JSFiddle even though I thought the code was almost exactly the same.

Code:
https://github.com/mattmazzola/fabric-slate-test/tree/slate-bug
Note: the specific branch `slate-bug` not `master`. 

I was suspicious it was a conflict of the component Fabric I was using so I was trying to combine it with that, but then was able to reproduce without the framework.

JSFiddle Attempt:
https://jsfiddle.net/mattmazzola/yw726bzn/

Maybe someone can continue off this one to reproduce there. Only thing I can think of is that the HTML markup is different in JS Fiddle since the page is actually embedded in iframe of another page and perhaps that ends up preventing the glitch

**Comment by mattmazzola** [comment]
Anymore information on this?

I was hoping now that the bug is isolated and reproducible someone with more knowledge about those scroll-to-selection scripts can understand the differences in behavior and then maybe add extra check to prevent the scroll jump.

**Comment by thevaleriemack** [comment]
@mattmazzola have you found a work around? Having same issue

**Comment by thevaleriemack** [comment]
My workaround is to not use this feature at all. For my purposes it is unnecessary so I just commented it out.

react-slate.es.js

    ...
    // Scroll to the selection, in case it's out of view.
    // scrollToSelection(native);
    ...

**Comment by mattmazzola** [comment]
Hmm, no we haven't found a solution for our app since it upgrading slate causes some breaking changes that we don't know how to fix at the moment, but I took another look at the [repo](https://github.com/mattmazzola/fabric-slate-test/tree/slate-bug) which has minimal reproduced issue and after upgrading slate to the latest version and the issue does no occur so maybe it was fixed.

See broken version with `slate@0.31.3`: http://slate-scroll-bug.surge.sh/
Working version with latest `slate@0.44.10`: http://slate-scroll-bug-fixed.surge.sh/

**Comment by thevaleriemack** [comment]
Yes I think option to disable it would be great. I'm still having this bug with 0.44.10.

I have found success implementing, in a pretty simple way, similar behavior that suits me. As an example, I wanted to keep the last node in view as a user is typing. I placed this code in the onChange function for my Editor component.

    // Scroll to bottom
    const focusBlock = value.focusBlock;
    const lastBlock = value.document.nodes.last();
    if (lastBlock && focusBlock && (lastBlock.key === focusBlock.key)) {
        const b = document.body;
        if (b.scrollHeight - b.scrollTop !== b.clientHeight) { // not at bottom
          scrollToBottom(b);
        }
    }

**Comment by mattmazzola** [comment]
> I'm still having this bug with 0.44.10

Does it still occur for you at the working version link I provided above?

I was using this version of Chrome: `Version 72.0.3626.109 (Official Build) (64-bit)`

If the issue still exists for you on that link I would guess the only difference could be browser inconsistencies

In our case we only have a single line input so the text can't increase downward by pressing enter. We intercept the enter key for submission and other functionality within the input.  This makes me think we may not need this functionality of trying to focus/follow the cursor as it moves down.

**Comment by dattran92** [comment]
I have the same problem with my richtext slate editor. this is my work around:

comment the scrollToSelection function as I think it calculate the height wrong or somehow.

// Scroll to the selection, in case it's out of view.
// scrollToSelection(native); 

add the following plugin to fix it:

```
// this plugins is to fix weird scroll behaviour
const plugins = [{
  onKeyDown: (e, editor, next) => {
    const element = e.target
    const bufferHeight = 35
    const { focusBlock } = editor.value
    let dataKey = focusBlock.key
    const focusElement = element.querySelector(`[data-key="${dataKey}"]`)

    const containerHeight = element.getBoundingClientRect().height
    const scrollTop = element.scrollTop
    const focusElOffsetTop = focusElement.offsetTop
    const focusElHeight = focusElement.getBoundingClientRect().height

    // console.log(element)
    // console.log(focusElement)
    // console.log({
    //   containerHeight,
    //   scrollTop,
    //   focusElOffsetTop,
    //   focusElHeight,
    // })

    const underViewPort = focusElOffsetTop + focusElHeight >= containerHeight + scrollTop
    const aboveViewPort = focusElOffsetTop <= scrollTop

    if (underViewPort) {
      setTimeout(() => {
        element.scroll(0, focusElOffsetTop + focusElHeight + bufferHeight - containerHeight)
      }, 200)
    } else if (aboveViewPort) {
      element.scroll(0, focusElOffsetTop - containerHeight)
    }

    next()
  }
}]
```

**Comment by mpkelly** [comment]
Thank you. That fixed the weird jumping I was seeing. 

> My workaround is to not use this feature at all. For my purposes it is unnecessary so I just commented it out.
> 
> react-slate.es.js
> 
> ```
> ...
> // Scroll to the selection, in case it's out of view.
> // scrollToSelection(native);
> ...
> ```

**Comment by ianstormtaylor** [comment]
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.
