### ISSUE TITLE
Render node according to selection state

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#192]
I'm trying to render a code block with a selector to choose the syntax.

It'll be better for my use case to render the selector only when the user is editing the code block (cursor in the code block).

I've tried:

```js
const CodeNode = React.createClass({
    ...

    render: function() {
        const { node, state, children } = this.props;
        const syntax = node.data.get('syntax', '');
        const isSelected = state.selection.hasFocusIn(node);

        return (
            <div className="DocumentEditor-CodeNode">
                {isSelected? <SyntaxSelector value={syntax} onChange={this.onChangeSyntax} /> : undefined}
                <pre>
                    <code>{children}</code>
                </pre>
            </div>
        );
    }
});
```

But the `CodeNode` compoment is only updated when I press `backspace`.

Is there something I'm missing ? or do I have to find a workaround?

**Comment by ianstormtaylor** [comment]
My guess is that the selector would properly render when the user clicks into the `CodeBlock`, but once they leave the `CodeBlock` then the selector doesn't hide itself. Is that the behavior you're seeing?

**Comment by SamyPesse** [comment]
It does not render when the user clicks in it, not even when typing, only when pressing backspace.

Moving to another block doesn't clear the selector neither.

**Comment by ianstormtaylor** [comment]
Okay, so I investigated this. Previously we needed to render selections "natively" (without re-rendering through React), for performance (when typing for instance). But actually don't need to do that, since we now check to see if a selection is the same as the current one before triggering the updating logic.

So good news, I just removed that bit in `0.8.3` and I believe your use case should work now!

**Comment by SamyPesse** [comment]
@ianstormtaylor Sorry for being late on this one, but there is still an issue.

The node is correctly rendered when selection is on it, but when selection is exiting (clicking on another node), the node is not rerendered.

> we now check to see if a selection is the same as the current one before triggering the updating logic

I guess you are relating to [lib/components/node.js#L62](https://github.com/ianstormtaylor/slate/blob/master/lib/components/node.js#L62) ?

The problem is that this condition doesn't handle passing from `isFocused=true` -> `isFocused=false`, the current `isFocused` can maybe be stored in the state of the node and compared in the `shouldComponentUpdate`.

**Comment by SamyPesse** [comment]
Also maybe it's not related to Slate, but I'm rendering an image void node, when clicking on the image, there is a small delay of ~1sec before the node is render and updated (the outline is shown, but the node is not yet rendered).

I'll try to make a jsfiddle to reproduce this.

**Comment by ianstormtaylor** [comment]
Fixed in `0.11.0`. Now the `<Void>` wrapper is implicit again, and expected to be styled via Javascript like you're doing! With the `suppressShouldComponentUpdate` as an option like we discussed (although for just "selected" cases you won't need it).
