### ISSUE TITLE
Edition with decorated text is unstable (code highlighting)

### ISSUE THREAD

**Issue by SamyPesse** [ianstormtaylor/slate#207]
Editing decorated text is unstable, for example with the [code highlighting](http://slatejs.org/#/code-highlighting?_k=dxscdc) example:

### Steps to reproduce

1. Position the cursor at the end of the `for (var i = 1; i <= 100; i++) {`
2. Press <kbd>Enter</kbd>
3. Type `var`
4. **Result:** a new line is inserted

### Video of the bug

![highlight](https://cloud.githubusercontent.com/assets/845425/17270064/a27b9780-5659-11e6-8e58-b58fd6a6c29a.gif)

This is one example of bug when editing the highlighted code block.

**Comment by ianstormtaylor** [comment]
Thanks for reporting man! Hard one to track down, but ended up figuring out that it was a few problems:

- A bug in the logic `onBeforeInput` uses to decide whether to update decorated text.
- A bug in the logic `<Leaf>` uses to decide when to append `\n` to the text.

Solved in `0.10.6`!

**Comment by SamyPesse** [comment]
Thanks @ianstormtaylor It's much better!

But.. there still an issue:

1. press enter twice
2. type `function`

![bug](https://cloud.githubusercontent.com/assets/845425/17327556/06ac6fac-58b9-11e6-88dd-79d0676f6f8a.gif)

**Comment by ianstormtaylor** [comment]
I'm not able to get it to repeat on the `code-highlighting` example, could you make a small JSFiddle that can reproduce it and I can check it out? Thanks man!

**Comment by SamyPesse** [comment]
You can reproduce it on the Slate highlighting example by entering `function` at the end of the code:

1. Move the cursor at the end of the last line
2. Press Enter
3. Type `function`

**Comment by ianstormtaylor** [comment]
Fixed in `0.10.9`! The `<Leaf>` text content needed to be checked against the DOM for cases where React is purposely out of sync to allow for faster native rendering.
