### ISSUE TITLE
Distribution as single file

### ISSUE THREAD

**Issue by podviaznikov** [ianstormtaylor/slate#229]
Is it possible to get slate.js as complete js file(bundle)?
I see that when I run `dist` it will produce `slate.js` but that file will require a lot of other files.

**Comment by ianstormtaylor** [comment]
Hey @podviaznikov! Great question. As you noticed there's a `slate.js` (and last I checked at `slate.min.js` as well) which are bundled for use as a standalone library. There are a few things that could be improved though, which sounds like exactly what you're talking about:

- [ ] **Ideally `react` would not be bundled with the output code.** I'm honestly not sure if this is the case or not, since I got sidetracked before fixing this. Right now the `npm run dist:bundle` scripts use `browserify-shim` to make `react` a global, but I'm not sure if it's configured properly.
- [ ] **Ideally `cheerio` would not be as huge in size as it is.** As of the current `0.20.0` version it includes the entire `lodash` dependency, instead of implementing one of the ways to include only parts of `lodash`. [This pull request](https://github.com/cheeriojs/cheerio/pull/864) implemented that functionality, but a new version of `cheerio` hasn't been published yet sadly. As soon as this is done, Slate's bundled size should drop by `~500KB` I believe.

I think those are the only two big issues, if you notice more, let me know! I haven't dug into those issues myself, but I'm down to merge in any pull requests that solve them.

**Comment by ianstormtaylor** [comment]
Okay, in `0.11.3` it no longer bundles `react`, `react-dom` or `immutable` by default, so you'll need to bring your own copies of those. Should fix the issue! I've added a guide to the docs for how to do that: https://github.com/ianstormtaylor/slate/blob/master/docs/guides/using-the-bundled-source.md

`cheerio` is still huge, but that should be fixed in time by the maintainers I hope.

**Comment by podviaznikov** [comment]
@ianstormtaylor thanks for the updated.
I just tried it with following html:
```

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <script src="https://npmcdn.com/react/dist/react.js"></script>
<script src="https://npmcdn.com/react-dom/dist/react-dom.js"></script>
<script src="https://npmcdn.com/immutable/dist/immutable.js"></script>
<script src="https://npmcdn.com/slate@0.11.3/dist/slate.js"></script>
  </head>
  <body>
    <div id="app">
    </div>

  </body>
</html>

```
and when I typed `Slate` in the web console I've got `VM2497:1 Uncaught ReferenceError: Slate is not defined(…)```.  Seems like some error exposing `Slate` var?

**Comment by ianstormtaylor** [comment]
Sorry about that, go with `0.11.4` actually I just fixed that!

**Comment by podviaznikov** [comment]
Yeah, thanks for the quick fix.

I already tried new version.
Still having trouble running simplest possible example.
I use same html page as above (with updated Slate version).
And in Web console I do
```
var editor = new Slate.Editor({state: Slate.Plain.deserialize("aaa"), plugins: []})
ReactDOM.render(editor, document.getElementById('app'))
```
I'm still getting
```
react.js:20156 Uncaught Error: ReactDOM.render(): Invalid component element. This may be caused by unintentionally loading two independent copies of React
```

Should my code even work? Or that is not correct way of rendering slate/react component?

**Comment by ianstormtaylor** [comment]
I haven't actually written non-Babel-ized code in a while 😄  but off the top of my head I think you'd need to be doing something along the lines of:

```js
var Editor = Slate.Editor
var Plain = Slate.Plain

var slate = Plain.deserialize('Some content...')
var editor = React.createElement(Editor, { state: state })
var app = document.getElementById('app')

ReactDOM.render(editor,  app)
```

**Comment by podviaznikov** [comment]
Thanks, now everything works!
